# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TECHFEST' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TECHFEST

pod 'Firebase/Core'
pod 'Firebase/Messaging'

 # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'



  target 'TECHFESTTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TECHFEST-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TECHFEST-tvOS

  target 'TECHFEST-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
